Name:           ros-hydro-gmapping
Version:        1.3.5
Release:        0%{?dist}
Summary:        ROS gmapping package

Group:          Development/Libraries
License:        CreativeCommons-by-nc-sa-2.0
URL:            http://ros.org/wiki/gmapping
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-openslam-gmapping
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-catkin >= 0.5.68
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-openslam-gmapping
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-tf

%description
This package contains a ROS wrapper for OpenSlam's Gmapping. The gmapping
package provides laser-based SLAM (Simultaneous Localization and Mapping), as a
ROS node called slam_gmapping. Using slam_gmapping, you can create a 2-D
occupancy grid map (like a building floorplan) from laser and pose data
collected by a mobile robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Aug 28 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 1.3.5-0
- Autogenerated by Bloom

